### ISSUE TITLE
Cleanup back ticks and apostrophes

### ISSUE THREAD

**Issue by elliotchance** [elliotchance/tracklist-editor#13]
Backticks (`) and UTF-8 apostrophes should be replaced with regular apostrophes.

**Comment by mkim219** [comment]
Hi @elliotchance. Can I work on this issue?

**Comment by elliotchance** [comment]
@mkim219 yes - you don't need to ask permission, just put in a PR

**Comment by mkim219** [comment]
@elliotchance  I have a question about this issue. If user inputs Backticks (`) and UTF-8 apostrophes, this should be converted into regular apostrophes?

**Comment by elliotchance** [comment]
Yes. So this really means backtick and variations of *smart quotes* - the 4 characters that make up the single and double for open an close. You might find this helpful: https://stackoverflow.com/questions/9401312/how-to-replace-curly-quotation-marks-in-a-string-using-javascript
