### ISSUE TITLE
Trim zeros from track numbers

### ISSUE THREAD

**Issue by elliotchance** [elliotchance/tracklist-editor#15]
Track numbers read as "01" should be converted to "1".

**Comment by mgrigajtis** [comment]
I've got this fixed if you want to assign it to me.

**Comment by elliotchance** [comment]
Thanks! Can you submit a PR?

**Comment by mgrigajtis** [comment]
https://github.com/elliotchance/tracklist-editor/pull/19

Has been submitted.
