### ISSUE TITLE
Tracklist goes wrong when there's credits in the tracklist

### ISSUE THREAD

**Issue by Maanstudio** [elliotchance/tracklist-editor#36]
When the tracklist has a ''show credits'' option, the tracklist is imported wrongly.

Example: 
https://www.discogs.com/release/1137659-Furtips-When-My-Baby-Smiles-At-Me-I-Go-To-Rio

**Comment by elliotchance** [comment]
@Maanstudio I wasn't able to replicate this because that URL isn't allowed. I've created a separate issue for that: #37 

I can't find how to get to the master release in dicsogs from that page?

**Comment by Maanstudio** [comment]
The album I used was Furtips – When My Baby Smiles At Me, I Go To Rio, but I think any album with credits in the tracklist should work.
